### ISSUE TITLE
Type incompatibility between module-soap and lib-innerbrowser

### ISSUE THREAD

**Issue by heinmekkes** [Codeception/module-soap#14]
The type of the SOAP::$client (line 81) property is incompatible (its nullability) with PhpBrowser::$client (line 127) 

InnerBrowser::_after tries to set its $client to null, but since the property is referenced by SOAP::$client (in SOAP::_before), this throws the error: ```Cannot assign null to reference held by property Codeception\Module\SOAP::$client of type Symfony\Component\BrowserKit\AbstractBrowser```

codeception/module-soap 2.0.1
codeception/module-phpbrowser 2.0.2
codeception/lib-innerbrowser 2.0.1

**Comment by Naktibalda** [comment]
Fixed in 2.0.2
